-- Baseline schema for riot-analizer.
--
-- This migration reproduces the schema that Hibernate previously generated via
-- `spring.jpa.hibernate.ddl-auto=update`, so that:
--   * a fresh database is created identically by Flyway, and
--   * `ddl-auto=validate` passes against it.
-- On databases that already contain these tables (created by the old
-- ddl-auto=update behaviour), Flyway's baseline-on-migrate marks version 1 as
-- already applied and does NOT run this script.

-- ---------------------------------------------------------------------------
-- player
-- ---------------------------------------------------------------------------
CREATE TABLE player (
    puuid               VARCHAR(255) NOT NULL,
    game_name           VARCHAR(255),
    tag_line            VARCHAR(255),
    summoner_id         VARCHAR(255),
    profile_icon_id     INTEGER,
    summoner_level      INTEGER,
    solo_tier           VARCHAR(255),
    solo_rank           VARCHAR(255),
    solo_league_points  INTEGER,
    solo_wins           INTEGER,
    solo_losses         INTEGER,
    flex_tier           VARCHAR(255),
    flex_rank           VARCHAR(255),
    flex_league_points  INTEGER,
    flex_wins           INTEGER,
    flex_losses         INTEGER,
    last_fetched        TIMESTAMP(6) WITH TIME ZONE,
    tracked             BOOLEAN NOT NULL,
    CONSTRAINT player_pkey PRIMARY KEY (puuid)
);

-- ---------------------------------------------------------------------------
-- matches  (named "matches" because "match" is a reserved word in PostgreSQL)
-- ---------------------------------------------------------------------------
CREATE TABLE matches (
    match_id        VARCHAR(255) NOT NULL,
    queue_id        INTEGER,
    game_creation   BIGINT NOT NULL,
    game_duration   INTEGER NOT NULL,
    game_version    VARCHAR(255),
    map_id          INTEGER,
    CONSTRAINT matches_pkey PRIMARY KEY (match_id)
);

-- ---------------------------------------------------------------------------
-- participant
-- ---------------------------------------------------------------------------
CREATE TABLE participant (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    match_id                    VARCHAR(255) NOT NULL,
    puuid                       VARCHAR(255),
    riot_id_game_name           VARCHAR(255),
    riot_id_tag_line            VARCHAR(255),
    champion_id                 INTEGER,
    champion_name               VARCHAR(255),
    team_id                     INTEGER,
    team_position               VARCHAR(255),
    win                         BOOLEAN NOT NULL,
    kills                       INTEGER NOT NULL,
    deaths                      INTEGER NOT NULL,
    assists                     INTEGER NOT NULL,
    total_cs                    INTEGER NOT NULL,
    vision_score                INTEGER NOT NULL,
    total_damage_to_champions   INTEGER NOT NULL,
    gold_earned                 INTEGER NOT NULL,
    item0                       INTEGER,
    item1                       INTEGER,
    item2                       INTEGER,
    item3                       INTEGER,
    item4                       INTEGER,
    item5                       INTEGER,
    item6                       INTEGER,
    summoner1_id                INTEGER,
    summoner2_id                INTEGER,
    CONSTRAINT participant_pkey PRIMARY KEY (id),
    CONSTRAINT fk_participant_match FOREIGN KEY (match_id) REFERENCES matches (match_id)
);

CREATE INDEX idx_participant_puuid ON participant (puuid);
CREATE INDEX idx_participant_champion ON participant (champion_name);

-- ---------------------------------------------------------------------------
-- match_timeline_cache
-- ---------------------------------------------------------------------------
CREATE TABLE match_timeline_cache (
    match_id        VARCHAR(255) NOT NULL,
    json            TEXT,
    schema_version  INTEGER,
    created_at      TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT match_timeline_cache_pkey PRIMARY KEY (match_id)
);
